# Configuration for git-buildpackage and affiliated tools

[DEFAULT]
debian-branch = debian/bullseye
pristine-tar = True
sign-tags = True
upstream-branch = upstream/bullseye

[import-orig]
merge-mode = replace

