# Configuration for git-buildpackage and affiliated tools

[DEFAULT]
debian-branch = debian/bookworm
pristine-tar = True
sign-tags = True
upstream-branch = upstream/bookworm

[import-orig]
merge-mode = replace
